version: '3.8'

services:
  ai-os-api:
    image: node:20-alpine
    networks:
      - network_public
    environment:
      - NODE_ENV=production
      - PORT=8000
      - REDIS_HOST=redis_redis
      - REDIS_PORT=6379
      - NEO4J_URI=bolt://neo4j_neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - POSTGRES_HOST=postgres_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ai_os
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ORCHESTRATOR_API_KEY=${ORCHESTRATOR_API_KEY}
      - UNIVERSAL_MEMORY_API_KEY=${UNIVERSAL_MEMORY_API_KEY}
      - CLAUDE_CODE_API_KEY=${CLAUDE_CODE_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ai-os-data:/data
    deploy:
      replicas: 2
      labels:
        - traefik.enable=true
        - traefik.docker.network=network_public
        - traefik.http.services.ai-os-api.loadbalancer.server.port=8000
        - traefik.http.routers.ai-os-api.rule=Host(`ai-os.allfluence.ai`)
        - traefik.http.routers.ai-os-api.entrypoints=websecure
        - traefik.http.routers.ai-os-api.tls=true
        - traefik.http.routers.ai-os-api.tls.certresolver=letsencryptresolver
        - traefik.http.routers.ai-os-api.service=ai-os-api
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    command:
      - sh
      - -c
      - |
        set -e
        echo "=== Iniciando deploy AI-OS API ==="
        
        # Instalar git
        apk add --no-cache git
        
        # Usar diretório temporário para clone
        WORK_DIR="/tmp/ai-os-clone"
        rm -rf $WORK_DIR
        mkdir -p $WORK_DIR
        
        # Clone o repositório
        echo "Clonando repositório..."
        git clone https://${GITHUB_TOKEN}@github.com/Pedrovaleriolopez/allfluence-core.git $WORK_DIR
        
        # Verificar estrutura
        echo "=== Estrutura do repositório ==="
        ls -la $WORK_DIR/
        
        # Procurar pelo projeto correto
        if [ -d "$WORK_DIR/ai-os" ]; then
          echo "Diretório ai-os encontrado!"
          cd $WORK_DIR/ai-os
        elif [ -f "$WORK_DIR/package.json" ]; then
          echo "package.json encontrado na raiz!"
          cd $WORK_DIR
        else
          echo "ERRO: Estrutura do projeto não reconhecida!"
          echo "Conteúdo do repositório:"
          find $WORK_DIR -type f -name "*.json" | head -20
          find $WORK_DIR -type d -maxdepth 3 | head -20
          exit 1
        fi
        
        # Instalar dependências e iniciar
        echo "Instalando dependências..."
        npm install --production
        
        echo "Executando build..."
        npm run build || echo "Build não necessário ou falhou"
        
        echo "Iniciando API..."
        npm run start:api || npm start || node server.js || node index.js
    working_dir: /app
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s

  ai-os-worker:
    image: node:20-alpine
    networks:
      - network_public
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis_redis
      - REDIS_PORT=6379
      - NEO4J_URI=bolt://neo4j_neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - POSTGRES_HOST=postgres_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ai_os
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ai-os-data:/data
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    command:
      - sh
      - -c
      - |
        set -e
        echo "=== Iniciando deploy AI-OS Worker ==="
        
        # Instalar git
        apk add --no-cache git
        
        # Usar diretório temporário para clone
        WORK_DIR="/tmp/ai-os-clone"
        rm -rf $WORK_DIR
        mkdir -p $WORK_DIR
        
        # Clone o repositório
        echo "Clonando repositório..."
        git clone https://${GITHUB_TOKEN}@github.com/Pedrovaleriolopez/allfluence-core.git $WORK_DIR
        
        # Verificar estrutura
        echo "=== Estrutura do repositório ==="
        ls -la $WORK_DIR/
        
        # Procurar pelo projeto correto
        if [ -d "$WORK_DIR/ai-os" ]; then
          echo "Diretório ai-os encontrado!"
          cd $WORK_DIR/ai-os
        elif [ -f "$WORK_DIR/package.json" ]; then
          echo "package.json encontrado na raiz!"
          cd $WORK_DIR
        else
          echo "ERRO: Estrutura do projeto não reconhecida!"
          echo "Conteúdo do repositório:"
          find $WORK_DIR -type f -name "*.json" | head -20
          find $WORK_DIR -type d -maxdepth 3 | head -20
          exit 1
        fi
        
        # Instalar dependências e iniciar
        echo "Instalando dependências..."
        npm install --production
        
        echo "Executando build..."
        npm run build || echo "Build não necessário ou falhou"
        
        echo "Iniciando Worker..."
        npm run start:worker || npm run worker || node worker.js
    working_dir: /app

  ai-os-scheduler:
    image: node:20-alpine
    networks:
      - network_public
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis_redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ai_os
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command:
      - sh
      - -c
      - |
        set -e
        echo "=== Iniciando deploy AI-OS Scheduler ==="
        
        # Instalar git
        apk add --no-cache git
        
        # Usar diretório temporário para clone
        WORK_DIR="/tmp/ai-os-clone"
        rm -rf $WORK_DIR
        mkdir -p $WORK_DIR
        
        # Clone o repositório
        echo "Clonando repositório..."
        git clone https://${GITHUB_TOKEN}@github.com/Pedrovaleriolopez/allfluence-core.git $WORK_DIR
        
        # Verificar estrutura
        echo "=== Estrutura do repositório ==="
        ls -la $WORK_DIR/
        
        # Procurar pelo projeto correto
        if [ -d "$WORK_DIR/ai-os" ]; then
          echo "Diretório ai-os encontrado!"
          cd $WORK_DIR/ai-os
        elif [ -f "$WORK_DIR/package.json" ]; then
          echo "package.json encontrado na raiz!"
          cd $WORK_DIR
        else
          echo "ERRO: Estrutura do projeto não reconhecida!"
          echo "Conteúdo do repositório:"
          find $WORK_DIR -type f -name "*.json" | head -20
          find $WORK_DIR -type d -maxdepth 3 | head -20
          exit 1
        fi
        
        # Instalar dependências e iniciar
        echo "Instalando dependências..."
        npm install --production
        
        echo "Executando build..."
        npm run build || echo "Build não necessário ou falhou"
        
        echo "Iniciando Scheduler..."
        npm run start:scheduler || npm run scheduler || node scheduler.js
    working_dir: /app

volumes:
  ai-os-data:
    driver: local

networks:
  network_public:
    external: true